name: smuff_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: 3.0.9
  intl: 0.18.1
  drift: 2.13.0
  sqlite3_flutter_libs: 0.5.17
  path_provider: 2.1.1
  path: 1.9.0
  get_it: 7.6.4
  dio: 5.3.3
  provider: 6.0.5
  uuid: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: 2.13.0
  build_runner: 2.4.6
  intl: ^0.18.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


flutter:
  uses-material-design: true
